/**
 * False Trigger Prevention - Session Duration Configuration
 *
 * WICHTIG: Diese Werte müssen mit den Konstanten in
 * esp32-firmware/highscore-sensor-c3.ino synchron bleiben!
 *
 * ESP32 Firmware Konstanten:
 * - MIN_SESSION_DURATION_MS = 100
 * - MAX_SESSION_DURATION_MS = 10000
 */

export const MIN_SESSION_DURATION_MS = 100;
export const MAX_SESSION_DURATION_MS = 10000;

// Default-Werte (entsprechen den Firmware-Defaults)
export const DEFAULT_MIN_SESSION_DURATION_MS = 800;
export const DEFAULT_MAX_SESSION_DURATION_MS = 4500;

// Slider-Ranges für bessere UX (Min-Slider: 100-2000ms, Max-Slider: 1000-10000ms)
// WICHTIG: Diese Werte müssen innerhalb der globalen Limits liegen:
//   MIN_SESSION_DURATION_MS <= MIN_DURATION_SLIDER_MAX <= MAX_SESSION_DURATION_MS
//   MIN_SESSION_DURATION_MS <= MAX_DURATION_SLIDER_MIN <= MAX_SESSION_DURATION_MS
export const MIN_DURATION_SLIDER_MAX = 2000;  // Obere Grenze für Min-Dauer Slider
export const MAX_DURATION_SLIDER_MIN = 1000;  // Untere Grenze für Max-Dauer Slider

// **FIX v8.5**: Validierung der Slider-Ranges zur Laufzeit
if (MIN_DURATION_SLIDER_MAX < MIN_SESSION_DURATION_MS || MIN_DURATION_SLIDER_MAX > MAX_SESSION_DURATION_MS) {
  throw new Error(`MIN_DURATION_SLIDER_MAX (${MIN_DURATION_SLIDER_MAX}) must be between MIN_SESSION_DURATION_MS (${MIN_SESSION_DURATION_MS}) and MAX_SESSION_DURATION_MS (${MAX_SESSION_DURATION_MS})`);
}

if (MAX_DURATION_SLIDER_MIN < MIN_SESSION_DURATION_MS || MAX_DURATION_SLIDER_MIN > MAX_SESSION_DURATION_MS) {
  throw new Error(`MAX_DURATION_SLIDER_MIN (${MAX_DURATION_SLIDER_MIN}) must be between MIN_SESSION_DURATION_MS (${MIN_SESSION_DURATION_MS}) and MAX_SESSION_DURATION_MS (${MAX_SESSION_DURATION_MS})`);
}

if (DEFAULT_MIN_SESSION_DURATION_MS < MIN_SESSION_DURATION_MS || DEFAULT_MIN_SESSION_DURATION_MS > MAX_SESSION_DURATION_MS) {
  throw new Error(`DEFAULT_MIN_SESSION_DURATION_MS (${DEFAULT_MIN_SESSION_DURATION_MS}) must be between MIN_SESSION_DURATION_MS (${MIN_SESSION_DURATION_MS}) and MAX_SESSION_DURATION_MS (${MAX_SESSION_DURATION_MS})`);
}

if (DEFAULT_MAX_SESSION_DURATION_MS < MIN_SESSION_DURATION_MS || DEFAULT_MAX_SESSION_DURATION_MS > MAX_SESSION_DURATION_MS) {
  throw new Error(`DEFAULT_MAX_SESSION_DURATION_MS (${DEFAULT_MAX_SESSION_DURATION_MS}) must be between MIN_SESSION_DURATION_MS (${MIN_SESSION_DURATION_MS}) and MAX_SESSION_DURATION_MS (${MAX_SESSION_DURATION_MS})`);
}

if (DEFAULT_MIN_SESSION_DURATION_MS >= DEFAULT_MAX_SESSION_DURATION_MS) {
  throw new Error(`DEFAULT_MIN_SESSION_DURATION_MS (${DEFAULT_MIN_SESSION_DURATION_MS}) must be less than DEFAULT_MAX_SESSION_DURATION_MS (${DEFAULT_MAX_SESSION_DURATION_MS})`);
}
